import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import Providers from "../components/theme/providers";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import "@/app/style/globals.css";
import "animate.css";
import { ReactNode } from "react";
import Header from "../components/layout/header";
import Footer from "../components/layout/footer";
import ReduxProvider from "../redux/provider";
interface ILocaleLayoutProps {
  children: ReactNode;
  params: { locale: string };
}

export const metadata: Metadata = {
  title: "Food Ordering System",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "az" }];
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: ILocaleLayoutProps) {
  let messages;
  try {
    messages = (await import(`../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReduxProvider>
            <Providers>
              <Header />
              {children}
            </Providers>
          </ReduxProvider>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
